[metadata]
version = attr: dimod.__version__

[options]
include_package_data = True
packages = 
    dimod
    dimod.binary
    dimod.binary.cybqm
    dimod.constrained
    dimod.core
    dimod.discrete
    dimod.generators
    dimod.higherorder
    dimod.quadratic
    dimod.quadratic.cyqm
    dimod.reference
    dimod.reference.composites
    dimod.reference.samplers
    dimod.roof_duality
    dimod.serialization
    dimod.testing
    dimod.views
python_requires = >=3.10
zip_safe = False

[pycodestyle]
max-line-length = 100
