version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build-manylinux:
    parameters:
      manylinux-tag:
        type: string
      manylinux-arch:
        type: string
      python-version:
        type: string

    docker:
      - image: quay.io/pypa/<< parameters.manylinux-tag >>_<< parameters.manylinux-arch >>

    steps:
      - checkout

      - run:
          name: Build wheels
          command: |
            for py in /opt/python/cp*/bin/python; do
              ver=$("$py" -c 'import sys; print("{0.major}.{0.minor}".format(sys.version_info))')
              req=<< parameters.python-version >>
              [[ "$ver" != "${req:0:3}" ]] && continue
              "$py" -m pip wheel . -w ./wheelhouse --no-deps
            done

      - run:
          name: Bundle shared libraries into wheels
          command: |
            plat="<< parameters.manylinux-tag >>_<< parameters.manylinux-arch >>"
            for whl in ./wheelhouse/*.whl; do
              auditwheel repair "$whl" --plat "$plat" -w ./distotheque
            done

      - store_artifacts: &store-dist
          path: distotheque

      - persist_to_workspace: &persist-dist
          root: distotheque
          paths: .

  build-sdist:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      - run: &build-sdist
          name: Build sdist
          command: |
            python -m venv env
            . env/bin/activate
            pip install -r requirements.txt
            python setup.py sdist -d ./distotheque

      - store_artifacts: *store-dist

      - persist_to_workspace: *persist-dist


workflows:
  build-test-deploy:
    jobs:
      - build-sdist:
          filters: &always-run  # required because it's indirectly required by the deploy job that runs on tags only
            tags:
              only: /.*/

      - build-manylinux:
          name: build-<< matrix.manylinux-tag >>_<< matrix.manylinux-arch >>-py<< matrix.python-version >>
          matrix:
            parameters:
              manylinux-tag: ["manylinux1", "manylinux2014"]
              manylinux-arch: ["x86_64"]
              python-version: &python-versions ["3.6.8", "3.7.9", "3.8.9", "3.9.4"]
          filters:
            <<: *always-run
